version: 2
jobs:
  build:
    working_directory: ~/eslint-config-storylog
    docker:
      - image: circleci/node:8.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn run lint
